[package]
name = "injector"
version = "0.1.0"
edition = "2021"

[dependencies]
ashpd = { version = "0.12", features = ["tokio"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread", "time"] }
zbus = "4"
thiserror = "1.0"
async-trait = "0.1"