name: Setup ColdVox Dependencies
description: Install system deps, libvosk, and Rust toolchain
inputs:
  skip-toolchain:
    description: Skip Rust toolchain setup (for jobs with custom toolchain)
    required: false
    default: 'false'
runs:
  using: composite
  steps:
    - name: Install system dependencies
      shell: bash
      run: |
        # Detect package manager and install appropriate packages
        if command -v dnf >/dev/null 2>&1; then
          # Fedora/RHEL/Nobara
          sudo dnf install -y --skip-unavailable \
            alsa-lib-devel \
            xdotool \
            libXtst-devel \
            wget \
            unzip \
            @development-tools
        elif command -v apt-get >/dev/null 2>&1; then
          # Ubuntu/Debian
          sudo apt-get update
          sudo apt-get install -y \
            libasound2-dev \
            libxdo-dev \
            libxtst-dev \
            wget \
            unzip \
            build-essential
        else
          echo "ERROR: Unsupported package manager" >&2
          exit 1
        fi

    - name: Validate libvosk installation
      shell: bash
      run: |
        echo "Validating pre-installed libvosk..."
        if [ ! -f "/usr/local/lib/libvosk.so" ]; then
          echo "ERROR: libvosk.so not found, run setup-permanent-libvosk.sh on runner"
          exit 1
        fi
        if [ ! -f "/usr/local/include/vosk_api.h" ]; then
          echo "ERROR: vosk_api.h not found, run setup-permanent-libvosk.sh on runner"
          exit 1
        fi
        # Ensure libvosk is in dynamic linker cache
        export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
        if ! ldconfig -p | grep -q vosk; then
          echo "WARNING: libvosk not in linker cache, refreshing..."
          sudo ldconfig
        fi
        echo "✅ libvosk available at /usr/local/lib/libvosk.so"
        echo "✅ libvosk cached in dynamic linker"

    - name: Setup Rust toolchain
      if: inputs.skip-toolchain != 'true'
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy

    - name: Cache Cargo
      uses: Swatinem/rust-cache@v2
      with:
        key: "nobara-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}"
        restore-keys: |
          nobara-${{ runner.os }}-
