name: Setup ColdVox Dependencies
description: Install system deps, libvosk, and Rust toolchain
inputs:
  skip-toolchain:
    description: Skip Rust toolchain setup (for jobs with custom toolchain)
    required: false
    default: "false"
runs:
  using: composite
  steps:
    - name: Confirm runner provisioning expectations
      shell: bash
      run: |
        set -euo pipefail
        echo "--- Runner Provisioning Assumptions ---"
        echo "The ColdVox runner action now assumes the self-hosted runner is pre-provisioned"
        echo "with the desktop automation and multimedia dependencies documented in"
        echo "docs/dev/runnerAgent/RunnerAgent.md. Direct command/library verification has"
        echo "been removed to avoid failing fast on partially provisioned systems; downstream"
        echo "tests will surface any missing tools in a more actionable context."
        echo ""
        echo "If you encounter missing dependency errors during later workflow steps, refer to"
        echo "docs/dev/runnerAgent/RunnerAgent.md#interactive-dependency-management for the"
        echo "recommended package list."

    - name: Setup Rust toolchain
      if: inputs.skip-toolchain != 'true'
      uses: dtolnay/rust-toolchain@v1
      with:
        toolchain: stable
        components: rustfmt, clippy

    - name: Cache Cargo
      uses: Swatinem/rust-cache@v2
      with:
        key: "nobara-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}"
