version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "23:00"
    commit-message:
      prefix: "chore(deps)"
    labels:
      - "dependencies"
      - "github-actions"
    # Group updates to reduce PR noise
    groups:
      actions:
        patterns:
          - "*"
  
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "23:00"
    commit-message:
      prefix: "chore(deps)"
    labels:
      - "dependencies"
      - "rust"
    # Don't update workspace members
    ignore:
      - dependency-name: "coldvox-*"