# ColdVox default configuration file
# All options below are shown with their default values and comments.

# Top-level settings
resampler_quality = "balanced"
activation_mode = "vad"
enable_device_monitor = true
device = "" # Leave empty to use system default

[injection]
# Core behavior
fail_fast = false                # Exit immediately if all injection methods fail
allow_kdotool = false            # Enable kdotool fallback (KDE/X11)
allow_enigo = false              # Enable enigo fallback (input simulation)
inject_on_unknown_focus = true   # Allow injection when focus is unknown
require_focus = false            # Require editable focus for injection
pause_hotkey = ""                # Hotkey to pause/resume injection (e.g., "Ctrl+Alt+P")
redact_logs = true               # Redact text in logs for privacy

# Timing and latency
max_total_latency_ms = 800       # Max latency for a single injection call (ms)
per_method_timeout_ms = 250      # Timeout for each method attempt (ms)
paste_action_timeout_ms = 200    # Timeout for paste actions (ms)

# Cooldown/backoff
cooldown_initial_ms = 10000      # Initial cooldown after failure (ms)
cooldown_backoff_factor = 2.0    # Exponential backoff factor
cooldown_max_ms = 300000         # Max cooldown period (ms)

# Injection behavior
injection_mode = "auto"          # "keystroke", "paste", or "auto"
keystroke_rate_cps = 20          # Keystroke rate (chars/sec)
max_burst_chars = 50             # Max chars per burst
paste_chunk_chars = 500          # Chunk size for paste ops
chunk_delay_ms = 30              # Delay between paste chunks (ms)

# Focus/window management
focus_cache_duration_ms = 200    # Cache duration for focus status (ms)
enable_window_detection = true   # Enable window manager integration
clipboard_restore_delay_ms = 500 # Delay before restoring clipboard (ms)
discovery_timeout_ms = 1000      # Timeout for window discovery (ms)

# App allow/block lists
allowlist = []                   # List of allowed app patterns (regex)
blocklist = []                   # List of blocked app patterns (regex)

# Success rate tuning
min_success_rate = 0.3           # Minimum success rate before fallback
min_sample_size = 5              # Samples before trusting success rate

[stt]
# Plugin selection
preferred = "vosk"               # Preferred STT plugin
fallbacks = ["onnx"]             # Fallback plugins in order of preference
require_local = true             # Require local (non-cloud) plugins only
max_mem_mb = 4096                # Max memory for STT models (MB)
language = "en-us"               # Desired language code

# Failover and garbage collection
failover_threshold = 3           # Consecutive failures before failover
failover_cooldown_secs = 300     # Cooldown after failover (seconds)
model_ttl_secs = 3600            # Time-to-live for unused models (seconds)
disable_gc = false               # Disable model garbage collection

# Debugging and metrics
metrics_log_interval_secs = 60   # Interval for logging STT metrics
debug_dump_events = false        # Dump detailed STT events to logs
auto_extract = true              # Automatically extract models from archives