# Nextest configuration for ColdVox
# Minimal configuration with sensible defaults for retries and timeouts

[profile.default]
retries = 2
fail-fast = false
status-level = "failures"
final-status-level = "flaky"
slow-timeout = { period = "120s", terminate-after = 2 }

# Profile for CI environments
[profile.ci]
retries = 3
fail-fast = false
status-level = "all"
final-status-level = "flaky"
slow-timeout = { period = "120s", terminate-after = 2 }

# Profile for local development with more verbose output
[profile.dev]
retries = 1
fail-fast = false
status-level = "failures"
final-status-level = "flaky"
slow-timeout = { period = "60s", terminate-after = 1 }