name: Benchmarks

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]
    paths:
      - 'crates/**'
      - 'Cargo.toml'
      - 'Cargo.lock'
      - '.github/workflows/benchmarks.yml'

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: benchmarks-${{ github.ref }}
  cancel-in-progress: true

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.1.7
      - uses: dtolnay/rust-toolchain@1482605bfc5719782e1267fd0c0cc350fe7646b8 # v1
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@23bce251a8cd2ffc3c1075eaa2367cf899916d84 # v2.7.3
      
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libasound2-dev
      
      - name: Run benchmarks
        run: |
          # Run Criterion benches with minimal features to avoid compilation issues
          cargo bench --bench text_chunking_bench --no-default-features --features silero -- --quiet
      
      - name: Store benchmark result (Criterion)
        uses: benchmark-action/github-action-benchmark@4de1bed97a47495fc4c5404952da0499e31f5c29 # v1.20.3
        with:
          name: 'Criterion: text_chunking'
          tool: 'criterion'
          output-file-path: target/criterion
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: false
          comment-on-alert: true
          alert-threshold: '120%'
          fail-on-alert: false
          gh-pages-branch: gh-pages
          benchmark-data-dir-path: dev/bench
          skip-fetch-gh-pages: false
          comment-always: false
          summary-always: false
          save-data-file: true