name: Benchmarks

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]
    paths:
      - "crates/**"
      - "Cargo.toml"
      - "Cargo.lock"
      - ".github/workflows/benchmarks.yml"
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: benchmarks-${{ github.ref }}
  cancel-in-progress: true

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493 # v4.1.7
      - uses: dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9 # v1
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@98c8021b550208e191a6a3145459bfc9fb29c4c0 # v2.8.0
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libasound2-dev
      - name: Run benchmarks
        run: |
          # Run Criterion benches with minimal features to avoid compilation issues
          cargo bench --bench text_chunking_bench --no-default-features --features silero -- --quiet
      - name: Store benchmark result (Criterion)
        uses: benchmark-action/github-action-benchmark@4e0b38bc48375986542b13c0d8976b7b80c60c00 # v1.20.5
        with:
          name: "Criterion: text_chunking"
          tool: "criterion"
          output-file-path: target/criterion
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: false
          comment-on-alert: true
          alert-threshold: "120%"
          fail-on-alert: false
          gh-pages-branch: gh-pages
          benchmark-data-dir-path: dev/bench
          skip-fetch-gh-pages: false
          comment-always: false
          summary-always: false
          save-data-file: true
