name: Compositor Test Matrix

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *' # 2 AM every day

jobs:
  build:
    runs-on: [self-hosted, Linux, X64]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Build test suite
        run: cargo build --release --bin coldvox-text-injection
      - name: Upload test binary
        uses: actions/upload-artifact@v3
        with:
          name: test-binary
          path: target/release/coldvox-text-injection
          retention-days: 1

  test-matrix:
    needs: build
    runs-on: [self-hosted, Linux, X64, vm-host] # Custom label for the runner host
    strategy:
      fail-fast: false
      matrix:
        compositor: [fedora-xfce]
    steps:
      - uses: actions/checkout@v3
      - name: Download test binary
        uses: actions/download-artifact@v3
        with:
          name: test-binary
          path: /tmp/
      - name: Run tests on ${{ matrix.compositor }}
        env:
          # The CI_SSH_KEY should be configured as a secret in the GitHub repository settings.
          # It should contain the private key that corresponds to the public key
          # baked into the Packer VM images.
          CI_SSH_KEY: ${{ secrets.CI_VM_SSH_KEY }}
        run: |
          chmod +x /tmp/coldvox-text-injection
          chmod +x testing-infra/scripts/ci-run-vm-test.sh
          testing-infra/scripts/ci-run-vm-test.sh ${{ matrix.compositor }} /tmp/coldvox-text-injection
      - name: Upload results
        if: always() # Upload results even if the test fails
        uses: actions/upload-artifact@v3
        with:
          name: test-results-${{ matrix.compositor }}
          path: results/${{ matrix.compositor }}/
          retention-days: 7