name: Generate Dependency Graphs

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: dependency-graphs-${{ github.ref }}
  cancel-in-progress: true

env:
  RUST_BACKTRACE: 1
  CARGO_TERM_COLOR: always

jobs:
  generate-dependency-graphs:
    name: Generate and Update Dependency Graphs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.1.7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9 # v1
        with:
          toolchain: stable

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@98c8021b550208e191a6a3145459bfc9fb29c4c0 # v2.8.0

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y graphviz

      - name: Install cargo-depgraph
        run: cargo install cargo-depgraph

      - name: Create dependency graphs directory
        run: mkdir -p docs/dependency-graphs

      - name: Generate workspace dependency graph
        run: |
          cargo depgraph --workspace-only > docs/dependency-graphs/workspace-deps.dot
          dot -Tpng docs/dependency-graphs/workspace-deps.dot -o docs/dependency-graphs/workspace-deps.png
          dot -Tsvg docs/dependency-graphs/workspace-deps.dot -o docs/dependency-graphs/workspace-deps.svg

      - name: Generate full dependency graph
        run: |
          cargo depgraph --all-deps > docs/dependency-graphs/full-deps.dot
          # Generate SVG only for full deps (PNG would be too large for git)
          dot -Tsvg docs/dependency-graphs/full-deps.dot -o docs/dependency-graphs/full-deps.svg

      - name: Check for changes
        id: verify-changed-files
        run: |
          if git diff --quiet docs/dependency-graphs/; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push dependency graphs
        if: steps.verify-changed-files.outputs.changed == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add docs/dependency-graphs/
          git commit -m "Update dependency graphs [skip ci]"
          git push
