name: Feature Matrix Tests

on:
  # Weekly comprehensive testing
  schedule:
    - cron: '0 2 * * 1'
  # Manual trigger
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: feature-matrix-${{ github.ref }}
  cancel-in-progress: true

jobs:
  feature-combinations:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493 # v4.1.7
      - uses: dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9 # v1
        with:
          toolchain: stable
      - name: Install cargo-hack
        run: cargo install cargo-hack --locked
      - uses: Swatinem/rust-cache@98c8021b550208e191a6a3145459bfc9fb29c4c0 # v2.8.0
      
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libasound2-dev libxdo-dev libxtst-dev
      
      - name: Test feature combinations for critical crates
        run: |
          # Test each feature in isolation and combinations
          cargo hack test --each-feature -p coldvox-audio
          cargo hack test --each-feature -p coldvox-vad
          cargo hack test --each-feature -p coldvox-text-injection
          
          # Skip GUI and Vosk crates (require special setup)
          cargo hack test --each-feature --workspace \
            --exclude coldvox-gui \
            --exclude coldvox-stt-vosk