name: Runner Test

on:
  workflow_dispatch:
  push:
    branches:
      - fedora-runner-test
    paths:
      - '.github/workflows/runner-test.yml'

jobs:
  test-runner:
    name: Test Self-Hosted Runner
    runs-on: [self-hosted, Linux, X64]
    timeout-minutes: 5
    
    steps:
      - name: Hello World
        run: |
          echo "Hello from self-hosted runner!"
          echo "Time: $(date)"
          echo "Hostname: $(hostname)"
          echo "User: $(whoami)"
          echo "PWD: $(pwd)"
      - name: Runner Diagnostics
        run: |
          echo "OS Release:" && cat /etc/os-release || true
          echo "Uname:" && uname -a
          echo "CPU Info (first 5 lines):" && grep -m5 'model name' /proc/cpuinfo || true
          echo "Memory:" && free -h || true
          echo "Disk:" && df -h / || true
          echo "Rust version:" && command -v rustc && rustc --version || echo 'rustc not installed'
          echo "Git version:" && git --version || true
          echo "Environment labels: $RUNNER_NAME ($RUNNER_OS/$RUNNER_ARCH)"