# .github/workflows/runner-diagnostic.yml
name: Runner Diagnostic

on:
  workflow_dispatch:

jobs:
  diagnose:
    name: Run Diagnostic Checks
    runs-on: ${{ contains(github.event.inputs.runner, 'self-hosted') && fromJSON('["self-hosted", "Linux", "X64", "fedora", "nobara"]') || 'ubuntu-latest' }} # Ensure this matches my runner's labels

    steps:
      - name: 1. Print Runner Environment Details
        run: |
          echo "--- Runner Identity ---"
          echo "User: $(whoami)"
          echo "Home: $HOME"
          echo "pwd: $(pwd)"
          echo ""
          echo "--- OS Information ---"
          cat /etc/os-release || true
          echo ""
          echo "--- PATH ---"
          echo "$PATH"

      - name: 2. Test Network and DNS from Runner
        run: |
          echo "--- Testing DNS resolution for codeload.github.com ---"
          if command -v dig >/dev/null 2>&1; then
            dig codeload.github.com || echo "dig failed"
          else
            echo "dig not installed"
          fi
          echo ""
          echo "Attempting getent hosts lookup:"
          getent hosts codeload.github.com || echo "getent failed"
          echo ""
          echo "--- Testing HTTPS connection to codeload.github.com ---"
          curl -v --connect-timeout 10 --retry 3 --retry-delay 2 https://codeload.github.com || echo "curl failed"

      - name: 3. Test Package Manager and Sudo Permissions
        run: |
          echo "--- Checking sudo capabilities ---"
          if sudo -n true 2>/dev/null; then
            echo "Sudo access without password confirmed."
            echo "--- Attempting to install 'xdotool' (as a test) ---"
            sudo dnf install -y --skip-unavailable xdotool || echo "xdotool install failed"
            echo "--- Verifying xdotool installation ---"            
            command -v xdotool && xdotool --version || echo "xdotool not available"
          else
            echo "ERROR: Sudo requires a password or is not configured for this user."
            exit 1
